openapi: 3.0.0
info:
  title: Chat API
  version: 1.0.0
paths:
  /api/chat:
    post:
      summary: Handle chat messages and return AI responses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                conversation_id:
                  type: string
                selected_text:
                  type: string
                page_url:
                  type: string
              required:
                - message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                        metadata:
                          type: object
                          properties:
                            module:
                              type: string
                            chapter:
                              type: string
                            source_file:
                              type: string
                        score:
                          type: number
                  conversation_id:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Bad request
        '500':
          description: Internal server error
