openapi: 3.0.0
info:
  title: Conversations API
  version: 1.0.0
paths:
  /api/conversations/{conversation_id}:
    get:
      summary: Retrieve conversation history
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        role:
                          type: string
                        content:
                          type: string
                        sources:
                          type: array
                          items:
                            type: object
                        created_at:
                          type: string
                          format: date-time
        '404':
          description: Conversation not found
        '500':
          description: Internal server error
